In [14]:
import json

import numpy as np
import pandas as pd
import httpx2

In [2]:
df = pd.read_parquet('assessment-reprocessed.parquet')

df.shape

(642, 52)

In [3]:
len(df[df.tiling_compatible == True])

144

In [16]:
res = df[df.collection_concept_id == "C3880514013-LARC_CLOUD"].iloc[0].to_dict()
res

{'collection_concept_id': 'C3880514013-LARC_CLOUD',
 'collection_short_name_and_version': 'CER_GEO_Ed4_MET05_FD.V02',
 'concept_id': 'G3927638814-LARC_CLOUD',
 'data_center': 'NASA/LARC/SD/ASDC',
 'data_url': 's3://asdc-prod-protected/CERES/CER_GEO_Ed4_MET05_FD_V02/2004.053/CER_GEO_Ed4_MET05_FD_V02_2004.053.0030.04K.nc',
 'backend': 'xarray',
 'format': nan,
 'extension': 'nc',
 'tiling_compatible': False,
 'incompatible_reason': 'bbox_request_failed',
 'error_message': 'BBox probe failed with HTTP status 400.',
 'tiles_url': 'https://v4jec6i5c0.execute-api.us-west-2.amazonaws.com/xarray/bbox/8,-60,118,60.png?collection_concept_id=C3880514013-LARC_CLOUD&granule_ur=CER_GEO_Ed4_MET05_FD_V02_2004.053.0030.04K.nc&variables=view_zenith_angle&sel=grid_lat%3Dnearest%3A%3A0&sel=grid_lon%3Dnearest%3A%3A63&sel=image_y%3Dnearest%3A%3A625.5&sel=image_x%3Dnearest%3A%3A626.5',
 'variable': 'view_zenith_angle',
 'data_variables': '["tisa_record", "mc_directory_header", "vis_063_calib", "temp_ir_calib", "temp_wv_calib", "lbtm_netcdf_version", "base_time", "time_offset", "solar_zenith_angle", "view_zenith_angle", "relative_azimuth_angle", "clearsky_vis_reflectance", "skin_temperature", "clearsky_ir_temperature", "scanline_time", "pixel_sza", "pixel_vza", "pixel_aza", "reflectance_vis", "visible_count", "temperature_sir", "temperature_67", "temperature_ir", "temperature_sw", "cloud_ir_emittance", "cloud_phase", "cloud_visible_optical_depth", "cloud_particle_size", "cloud_lwp_iwp", "cloud_effective_temperature", "cloud_effective_pressure", "cloud_effective_height", "cloud_top_temperature", "cloud_top_pressure", "cloud_top_height", "cloud_bottom_temperature", "cloud_bottom_pressure", "cloud_bottom_height", "pixel_skin_temperature"]',
 'num_granules': 59604,
 'processing_level': '2',
 'groups': '[]',
 'assessment_status': 'inconclusive',
 'failure_stage': 'bbox_probe',
 'failure_category': 'render_error',
 'failure_subcategory': 'bbox_probe_attempt_limit_exceeded',
 'error_code': 'bbox_probe_attempt_limit_exceeded',
 'error_detail': 'BBox probe failed with HTTP status 400.',
 'failure_http_status_code': 400.0,
 'failure_endpoint': '/xarray/bbox',
 'failure_url': 'https://v4jec6i5c0.execute-api.us-west-2.amazonaws.com/xarray/bbox/8,-60,118,60.png?collection_concept_id=C3880514013-LARC_CLOUD&granule_ur=CER_GEO_Ed4_MET05_FD_V02_2004.053.0030.04K.nc&variables=view_zenith_angle&sel=grid_lat%3Dnearest%3A%3A0&sel=grid_lon%3Dnearest%3A%3A63&sel=image_y%3Dnearest%3A%3A625.5&sel=image_x%3Dnearest%3A%3A626.5',
 'raw_error_body': '{"detail":"A \'temporal\' parameter is required"}',
 'granule_concept_id': 'G3927638814-LARC_CLOUD',
 'granule_ur': 'CER_GEO_Ed4_MET05_FD_V02_2004.053.0030.04K.nc',
 'assessed_asset_href': 's3://asdc-prod-protected/CERES/CER_GEO_Ed4_MET05_FD_V02/2004.053/CER_GEO_Ed4_MET05_FD_V02_2004.053.0030.04K.nc',
 'assessed_asset_extension': 'nc',
 'assessed_asset_scheme': 's3',
 'group': nan,
 'variables': '["view_zenith_angle"]',
 'selected_variable_source': 'fallback_exhaustive',
 'dimension_selectors': '["grid_lat=nearest::0", "grid_lon=nearest::63", "image_y=nearest::625.5", "image_x=nearest::626.5"]',
 'temporal': nan,
 'selected_dimension_source': 'grid_lat:coordinate_midpoint,grid_lon:coordinate_midpoint,image_y:coordinate_midpoint,image_x:coordinate_midpoint',
 'compatible_groups': '[]',
 'tested_groups': '[]',
 'granule_bbox': '[8.0, -60.0, 118.0, 60.0]',
 'probe_bbox': '[8.0, -60.0, 118.0, 60.0]',
 'bbox_status_code': 400.0,
 'bbox_error_body': '{"detail":"A \'temporal\' parameter is required"}',
 'bbox_error_snippet': '{"detail":"A \'temporal\' parameter is required"}',
 'bbox_url': 'https://v4jec6i5c0.execute-api.us-west-2.amazonaws.com/xarray/bbox/8,-60,118,60.png?collection_concept_id=C3880514013-LARC_CLOUD&granule_ur=CER_GEO_Ed4_MET05_FD_V02_2004.053.0030.04K.nc&variables=view_zenith_angle&sel=grid_lat%3Dnearest%3A%3A0&sel=grid_lon%3Dnearest%3A%3A63&sel=image_y%3Dnearest%3A%3A625.5&sel=image_x%3Dnearest%3A%3A626.5',
 'bbox_attempt_count': 10.0,
 'bbox_attempts': '[{"bbox": [8.0, -60.0, 118.0, 60.0], "dimension_selectors": ["grid_lat=nearest::0", "grid_lon=nearest::63", "image_y=nearest::625.5", "image_x=nearest::626.5"], "error_snippet": "{\\"detail\\":\\"A \'temporal\' parameter is required\\"}", "group": null, "selected_dimension_source": "grid_lat:coordinate_midpoint,grid_lon:coordinate_midpoint,image_y:coordinate_midpoint,image_x:coordinate_midpoint", "selected_variable_source": "compatibility_link", "status_code": 400, "temporal": null, "url": "https://v4jec6i5c0.execute-api.us-west-2.amazonaws.com/xarray/bbox/8,-60,118,60.png?collection_concept_id=C3880514013-LARC_CLOUD&granule_ur=CER_GEO_Ed4_MET05_FD_V02_2004.053.0030.04K.nc&variables=tisa_record&sel=grid_lat%3Dnearest%3A%3A0&sel=grid_lon%3Dnearest%3A%3A63&sel=image_y%3Dnearest%3A%3A625.5&sel=image_x%3Dnearest%3A%3A626.5", "variables": ["tisa_record"]}, {"bbox": [8.0, -60.0, 118.0, 60.0], "dimension_selectors": ["grid_lat=nearest::0", "grid_lon=nearest::63", "image_y=nearest::625.5", "image_x=nearest::626.5"], "error_snippet": "{\\"detail\\":\\"A \'temporal\' parameter is required\\"}", "group": null, "selected_dimension_source": "grid_lat:coordinate_midpoint,grid_lon:coordinate_midpoint,image_y:coordinate_midpoint,image_x:coordinate_midpoint", "selected_variable_source": "fallback_exhaustive", "status_code": 400, "temporal": null, "url": "https://v4jec6i5c0.execute-api.us-west-2.amazonaws.com/xarray/bbox/8,-60,118,60.png?collection_concept_id=C3880514013-LARC_CLOUD&granule_ur=CER_GEO_Ed4_MET05_FD_V02_2004.053.0030.04K.nc&variables=mc_directory_header&sel=grid_lat%3Dnearest%3A%3A0&sel=grid_lon%3Dnearest%3A%3A63&sel=image_y%3Dnearest%3A%3A625.5&sel=image_x%3Dnearest%3A%3A626.5", "variables": ["mc_directory_header"]}, {"bbox": [8.0, -60.0, 118.0, 60.0], "dimension_selectors": ["grid_lat=nearest::0", "grid_lon=nearest::63", "image_y=nearest::625.5", "image_x=nearest::626.5"], "error_snippet": "{\\"detail\\":\\"A \'temporal\' parameter is required\\"}", "group": null, "selected_dimension_source": "grid_lat:coordinate_midpoint,grid_lon:coordinate_midpoint,image_y:coordinate_midpoint,image_x:coordinate_midpoint", "selected_variable_source": "fallback_exhaustive", "status_code": 400, "temporal": null, "url": "https://v4jec6i5c0.execute-api.us-west-2.amazonaws.com/xarray/bbox/8,-60,118,60.png?collection_concept_id=C3880514013-LARC_CLOUD&granule_ur=CER_GEO_Ed4_MET05_FD_V02_2004.053.0030.04K.nc&variables=vis_063_calib&sel=grid_lat%3Dnearest%3A%3A0&sel=grid_lon%3Dnearest%3A%3A63&sel=image_y%3Dnearest%3A%3A625.5&sel=image_x%3Dnearest%3A%3A626.5", "variables": ["vis_063_calib"]}, {"bbox": [8.0, -60.0, 118.0, 60.0], "dimension_selectors": ["grid_lat=nearest::0", "grid_lon=nearest::63", "image_y=nearest::625.5", "image_x=nearest::626.5"], "error_snippet": "{\\"detail\\":\\"A \'temporal\' parameter is required\\"}", "group": null, "selected_dimension_source": "grid_lat:coordinate_midpoint,grid_lon:coordinate_midpoint,image_y:coordinate_midpoint,image_x:coordinate_midpoint", "selected_variable_source": "fallback_exhaustive", "status_code": 400, "temporal": null, "url": "https://v4jec6i5c0.execute-api.us-west-2.amazonaws.com/xarray/bbox/8,-60,118,60.png?collection_concept_id=C3880514013-LARC_CLOUD&granule_ur=CER_GEO_Ed4_MET05_FD_V02_2004.053.0030.04K.nc&variables=temp_ir_calib&sel=grid_lat%3Dnearest%3A%3A0&sel=grid_lon%3Dnearest%3A%3A63&sel=image_y%3Dnearest%3A%3A625.5&sel=image_x%3Dnearest%3A%3A626.5", "variables": ["temp_ir_calib"]}, {"bbox": [8.0, -60.0, 118.0, 60.0], "dimension_selectors": ["grid_lat=nearest::0", "grid_lon=nearest::63", "image_y=nearest::625.5", "image_x=nearest::626.5"], "error_snippet": "{\\"detail\\":\\"A \'temporal\' parameter is required\\"}", "group": null, "selected_dimension_source": "grid_lat:coordinate_midpoint,grid_lon:coordinate_midpoint,image_y:coordinate_midpoint,image_x:coordinate_midpoint", "selected_variable_source": "fallback_exhaustive", "status_code": 400, "temporal": null, "url": "https://v4jec6i5c0.execute-api.us-west-2.amazonaws.com/xarray/bbox/8,-60,118,60.png?collection_concept_id=C3880514013-LARC_CLOUD&granule_ur=CER_GEO_Ed4_MET05_FD_V02_2004.053.0030.04K.nc&variables=temp_wv_calib&sel=grid_lat%3Dnearest%3A%3A0&sel=grid_lon%3Dnearest%3A%3A63&sel=image_y%3Dnearest%3A%3A625.5&sel=image_x%3Dnearest%3A%3A626.5", "variables": ["temp_wv_calib"]}, {"bbox": [8.0, -60.0, 118.0, 60.0], "dimension_selectors": ["grid_lat=nearest::0", "grid_lon=nearest::63", "image_y=nearest::625.5", "image_x=nearest::626.5"], "error_snippet": "{\\"detail\\":\\"A \'temporal\' parameter is required\\"}", "group": null, "selected_dimension_source": "grid_lat:coordinate_midpoint,grid_lon:coordinate_midpoint,image_y:coordinate_midpoint,image_x:coordinate_midpoint", "selected_variable_source": "fallback_exhaustive", "status_code": 400, "temporal": null, "url": "https://v4jec6i5c0.execute-api.us-west-2.amazonaws.com/xarray/bbox/8,-60,118,60.png?collection_concept_id=C3880514013-LARC_CLOUD&granule_ur=CER_GEO_Ed4_MET05_FD_V02_2004.053.0030.04K.nc&variables=lbtm_netcdf_version&sel=grid_lat%3Dnearest%3A%3A0&sel=grid_lon%3Dnearest%3A%3A63&sel=image_y%3Dnearest%3A%3A625.5&sel=image_x%3Dnearest%3A%3A626.5", "variables": ["lbtm_netcdf_version"]}, {"bbox": [8.0, -60.0, 118.0, 60.0], "dimension_selectors": ["grid_lat=nearest::0", "grid_lon=nearest::63", "image_y=nearest::625.5", "image_x=nearest::626.5"], "error_snippet": "{\\"detail\\":\\"A \'temporal\' parameter is required\\"}", "group": null, "selected_dimension_source": "grid_lat:coordinate_midpoint,grid_lon:coordinate_midpoint,image_y:coordinate_midpoint,image_x:coordinate_midpoint", "selected_variable_source": "fallback_exhaustive", "status_code": 400, "temporal": null, "url": "https://v4jec6i5c0.execute-api.us-west-2.amazonaws.com/xarray/bbox/8,-60,118,60.png?collection_concept_id=C3880514013-LARC_CLOUD&granule_ur=CER_GEO_Ed4_MET05_FD_V02_2004.053.0030.04K.nc&variables=base_time&sel=grid_lat%3Dnearest%3A%3A0&sel=grid_lon%3Dnearest%3A%3A63&sel=image_y%3Dnearest%3A%3A625.5&sel=image_x%3Dnearest%3A%3A626.5", "variables": ["base_time"]}, {"bbox": [8.0, -60.0, 118.0, 60.0], "dimension_selectors": ["grid_lat=nearest::0", "grid_lon=nearest::63", "image_y=nearest::625.5", "image_x=nearest::626.5"], "error_snippet": "{\\"detail\\":\\"A \'temporal\' parameter is required\\"}", "group": null, "selected_dimension_source": "grid_lat:coordinate_midpoint,grid_lon:coordinate_midpoint,image_y:coordinate_midpoint,image_x:coordinate_midpoint", "selected_variable_source": "fallback_exhaustive", "status_code": 400, "temporal": null, "url": "https://v4jec6i5c0.execute-api.us-west-2.amazonaws.com/xarray/bbox/8,-60,118,60.png?collection_concept_id=C3880514013-LARC_CLOUD&granule_ur=CER_GEO_Ed4_MET05_FD_V02_2004.053.0030.04K.nc&variables=time_offset&sel=grid_lat%3Dnearest%3A%3A0&sel=grid_lon%3Dnearest%3A%3A63&sel=image_y%3Dnearest%3A%3A625.5&sel=image_x%3Dnearest%3A%3A626.5", "variables": ["time_offset"]}, {"bbox": [8.0, -60.0, 118.0, 60.0], "dimension_selectors": ["grid_lat=nearest::0", "grid_lon=nearest::63", "image_y=nearest::625.5", "image_x=nearest::626.5"], "error_snippet": "{\\"detail\\":\\"A \'temporal\' parameter is required\\"}", "group": null, "selected_dimension_source": "grid_lat:coordinate_midpoint,grid_lon:coordinate_midpoint,image_y:coordinate_midpoint,image_x:coordinate_midpoint", "selected_variable_source": "fallback_exhaustive", "status_code": 400, "temporal": null, "url": "https://v4jec6i5c0.execute-api.us-west-2.amazonaws.com/xarray/bbox/8,-60,118,60.png?collection_concept_id=C3880514013-LARC_CLOUD&granule_ur=CER_GEO_Ed4_MET05_FD_V02_2004.053.0030.04K.nc&variables=solar_zenith_angle&sel=grid_lat%3Dnearest%3A%3A0&sel=grid_lon%3Dnearest%3A%3A63&sel=image_y%3Dnearest%3A%3A625.5&sel=image_x%3Dnearest%3A%3A626.5", "variables": ["solar_zenith_angle"]}, {"bbox": [8.0, -60.0, 118.0, 60.0], "dimension_selectors": ["grid_lat=nearest::0", "grid_lon=nearest::63", "image_y=nearest::625.5", "image_x=nearest::626.5"], "error_snippet": "{\\"detail\\":\\"A \'temporal\' parameter is required\\"}", "group": null, "selected_dimension_source": "grid_lat:coordinate_midpoint,grid_lon:coordinate_midpoint,image_y:coordinate_midpoint,image_x:coordinate_midpoint", "selected_variable_source": "fallback_exhaustive", "status_code": 400, "temporal": null, "url": "https://v4jec6i5c0.execute-api.us-west-2.amazonaws.com/xarray/bbox/8,-60,118,60.png?collection_concept_id=C3880514013-LARC_CLOUD&granule_ur=CER_GEO_Ed4_MET05_FD_V02_2004.053.0030.04K.nc&variables=view_zenith_angle&sel=grid_lat%3Dnearest%3A%3A0&sel=grid_lon%3Dnearest%3A%3A63&sel=image_y%3Dnearest%3A%3A625.5&sel=image_x%3Dnearest%3A%3A626.5", "variables": ["view_zenith_angle"]}]',
 'bbox_probe_limited': True,
 'compatibility_status_code': nan,
 'compatibility_error_body': nan,

In [19]:
print(json.dumps(json.loads(res["compatibility_response"]), indent=2))

{
  "backend": "xarray",
  "compatible_groups": null,
  "concept_id": "C3880514013-LARC_CLOUD",
  "coordinates": {
    "grid_lat": {
      "dtype": "float32",
      "max": 59.5,
      "min": -59.5,
      "size": 120
    },
    "grid_lon": {
      "dtype": "float32",
      "max": 117.5,
      "min": 8.5,
      "size": 110
    },
    "image_x": {
      "dtype": "int32",
      "max": 1252.0,
      "min": 1.0,
      "size": 1252
    },
    "image_y": {
      "dtype": "int32",
      "max": 1250.0,
      "min": 1.0,
      "size": 1250
    },
    "latitude": {
      "dtype": "float32",
      "max": 63.72999954223633,
      "min": -63.6300048828125,
      "size": 1565000
    },
    "longitude": {
      "dtype": "float32",
      "max": 126.68999481201172,
      "min": -0.6899999976158142,
      "size": 1565000
    }
  },
  "datetime": [
    {
      "EndsAtPresentFlag": false,
      "RangeDateTimes": [
        {
          "BeginningDateTime": "2000-02-28T23:59:59.000Z",
          "EndingDateTime": "2007-01-25T23:59:59.000Z"
        }
      ]
    }
  ],
  "dimensions": {
    "calib_dim": 8,
    "grid_lat": 120,
    "grid_lon": 110,
    "image_x": 1252,
    "image_y": 1250,
    "mc_dirhed_size": 64,
    "tisa_dim": 20
  },
  "example_assets": "s3://asdc-prod-protected/CERES/CER_GEO_Ed4_MET05_FD_V02/2004.053/CER_GEO_Ed4_MET05_FD_V02_2004.053.0030.04K.nc",
  "granule_ur": "CER_GEO_Ed4_MET05_FD_V02_2004.053.0030.04K.nc",
  "incompatible_variables": {
    "base_time": {
      "dims": [],
      "reason": "missing recognized x/y dimensions"
    },
    "clearsky_ir_temperature": {
      "dims": [
        "grid_lat",
        "grid_lon"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "clearsky_vis_reflectance": {
      "dims": [
        "grid_lat",
        "grid_lon"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "cloud_bottom_height": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "cloud_bottom_pressure": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "cloud_bottom_temperature": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "cloud_effective_height": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "cloud_effective_pressure": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "cloud_effective_temperature": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "cloud_ir_emittance": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "cloud_lwp_iwp": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "cloud_particle_size": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "cloud_phase": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "cloud_top_height": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "cloud_top_pressure": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "cloud_top_temperature": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "cloud_visible_optical_depth": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "lbtm_netcdf_version": {
      "dims": [],
      "reason": "missing recognized x/y dimensions"
    },
    "mc_directory_header": {
      "dims": [
        "mc_dirhed_size"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "pixel_aza": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "pixel_skin_temperature": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "pixel_sza": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "pixel_vza": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "reflectance_vis": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "relative_azimuth_angle": {
      "dims": [
        "grid_lat",
        "grid_lon"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "scanline_time": {
      "dims": [
        "image_y"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "skin_temperature": {
      "dims": [
        "grid_lat",
        "grid_lon"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "solar_zenith_angle": {
      "dims": [
        "grid_lat",
        "grid_lon"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "temp_ir_calib": {
      "dims": [
        "calib_dim"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "temp_wv_calib": {
      "dims": [
        "calib_dim"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "temperature_67": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "temperature_ir": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "temperature_sir": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "temperature_sw": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "time_offset": {
      "dims": [],
      "reason": "missing recognized x/y dimensions"
    },
    "tisa_record": {
      "dims": [
        "tisa_dim"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "view_zenith_angle": {
      "dims": [
        "grid_lat",
        "grid_lon"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "vis_063_calib": {
      "dims": [
        "calib_dim"
      ],
      "reason": "missing recognized x/y dimensions"
    },
    "visible_count": {
      "dims": [
        "image_y",
        "image_x"
      ],
      "reason": "missing recognized x/y dimensions"
    }
  },
  "links": [
    {
      "href": "https://v4jec6i5c0.execute-api.us-west-2.amazonaws.com/xarray/WebMercatorQuad/tilejson.json?collection_concept_id=C3880514013-LARC_CLOUD&variables=tisa_record&temporal={temporal}",
      "rel": "tilejson",
      "title": "TileJSON",
      "type": "application/json"
    },
    {
      "href": "https://v4jec6i5c0.execute-api.us-west-2.amazonaws.com/xarray/WebMercatorQuad/map.html?collection_concept_id=C3880514013-LARC_CLOUD&variables=tisa_record&temporal={temporal}",
      "rel": "map",
      "title": "Map viewer",
      "type": "text/html"
    },
    {
      "href": "https://v4jec6i5c0.execute-api.us-west-2.amazonaws.com/xarray/tiles/WebMercatorQuad/{z}/{x}/{y}?collection_concept_id=C3880514013-LARC_CLOUD&variables=tisa_record&temporal={temporal}",
      "rel": "tile",
      "title": "Map tile",
      "type": "image/png"
    }
  ],
  "sample_asset_raster_info": null,
  "tileable_variables": [],
  "variables": {
    "base_time": {
      "dtype": "datetime64[ns]",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": []
    },
    "clearsky_ir_temperature": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        120,
        110
      ]
    },
    "clearsky_vis_reflectance": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        120,
        110
      ]
    },
    "cloud_bottom_height": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "cloud_bottom_pressure": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "cloud_bottom_temperature": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "cloud_effective_height": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "cloud_effective_pressure": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "cloud_effective_temperature": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "cloud_ir_emittance": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "cloud_lwp_iwp": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "cloud_particle_size": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "cloud_phase": {
      "dtype": "float64",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "cloud_top_height": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "cloud_top_pressure": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "cloud_top_temperature": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "cloud_visible_optical_depth": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "lbtm_netcdf_version": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": []
    },
    "mc_directory_header": {
      "dtype": "int32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        64
      ]
    },
    "pixel_aza": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "pixel_skin_temperature": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "pixel_sza": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "pixel_vza": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "reflectance_vis": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "relative_azimuth_angle": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        120,
        110
      ]
    },
    "scanline_time": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250
      ]
    },
    "skin_temperature": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        120,
        110
      ]
    },
    "solar_zenith_angle": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        120,
        110
      ]
    },
    "temp_ir_calib": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        8
      ]
    },
    "temp_wv_calib": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        8
      ]
    },
    "temperature_67": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "temperature_ir": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "temperature_sir": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "temperature_sw": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    },
    "time_offset": {
      "dtype": "datetime64[ns]",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": []
    },
    "tisa_record": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        20
      ]
    },
    "view_zenith_angle": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        120,
        110
      ]
    },
    "vis_063_calib": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        8
      ]
    },
    "visible_count": {
      "dtype": "float32",
      "max": null,
      "mean": null,
      "min": null,
      "p01": null,
      "p05": null,
      "p95": null,
      "p99": null,
      "shape": [
        1250,
        1252
      ]
    }
  }
}

In [10]:
httpx2.get("https://v4jec6i5c0.execute-api.us-west-2.amazonaws.com/xarray/bbox/-180,-40,180,40.png?collection_concept_id=C2251464495-POCLOUD&granule_ur=cyg.ddmi.s20250901-000000-e20250901-235959.l2.wind-mss.a21.d21&variables=sc_alt&sel=sample%3Dnearest%3A%3A516628.5&sel=ddm%3Dnearest%3A%3A2&sel=averaged_l1%3Dnearest%3A%3A-2147483647&temporal=2025-09-01T00:00:00Z")

In [4]:
counts = df['incompatible_reason'].value_counts(dropna=False).reset_index()
counts.columns = ['Value', 'Count']
print(counts)

                          Value  Count
0           bbox_request_failed    491
1                           NaN    144
2  compatibility_request_failed      6
3      granule_bbox_unavailable      1

In [225]:
df[df.incompatible_reason == 'cant_open_file']['error_message'].value_counts()

error_message
Error opening: 'NoneType' object has no attribute 'split'                                                                           25
Error opening: 'in <string>' requires string as left operand, not bytes                                                             11
Error opening: 'd_UTCTime_1'                                                                                                         8
Error opening: unhashable type: 'writeable void-scalar'                                                                              6
Error opening: 'd_UTCTime_4s'                                                                                                        4
                                                                                                                                    ..
Error opening: RetryError[<Future at 0x7f2e550f69c0 state=finished raised JSONDecodeError>]                                          1
Error opening: RetryError[<Future at 0x7f111c20ae10 state=finished raised JSONDecodeError>]                                          1
Error opening: RetryError[<Future at 0x7f5f15aab590 state=finished raised JSONDecodeError>]                                          1
Error opening: RetryError[<Future at 0x7f3e49d67c80 state=finished raised JSONDecodeError>]                                          1
Error opening: https://n5eil01u.ecs.nsidc.org/DP7/ICESAT2_PO/IS2CHM.001/2019.01.01/IS2CHM_CONUS_tile0_20190101-20211231_V1.0.tif     1
Name: count, Length: 66, dtype: int64

In [189]:
df[df.error_message == "Error opening: 'NoneType' object has no attribute 'split'"].collection_concept_id

1140      C1442068511-GES_DISC
1444      C1627516279-GES_DISC
1449      C1627516281-GES_DISC
1452      C1627516298-GES_DISC
2712      C1993479672-GES_DISC
3129      C2045794784-GES_DISC
3132      C2045794916-GES_DISC
3133      C2045794848-GES_DISC
3267      C2087131083-GES_DISC
3272      C2089270961-GES_DISC
3452    C2153552369-NSIDC_CPRD
3453    C2153551318-NSIDC_CPRD
4828    C2547589158-NSIDC_CPRD
5007    C2596864127-NSIDC_CPRD
5031    C2613553216-NSIDC_CPRD
Name: collection_concept_id, dtype: object

In [16]:
# Filter out None/NaN and empty arrays
subset_df = df[df['data_variables'].apply(
    lambda x: x is not None and (len(x) > 0 and x[0] != None)
)]
subset_df

,collection_concept_id,concept_id,data_center,data_url,backend,format,extension,tiling_compatible,incompatible_reason,error_message,tiles_url,variable,data_variables,num_granules,processing_level,groups
0,C1000000060-LARC_ASDC,G1533371667-LARC_ASDC,ASDC,https://asdc.larc.nasa.gov/data/CERES/GEO/Edit...,xarray,NETCDF-4,nc,False,tile_generation_failed,list index out of range,https://staging.openveda.cloud/api/titiler-cmr...,vis_063_calib,"[vis_063_calib, temp_nir_calib, temp_ir_calib,...",48317.0,2,None
106,C1000000922-LARC_ASDC,G1000713545-LARC_ASDC,ASDC,https://asdc.larc.nasa.gov/data/FIRE/FIRE_ACE_...,xarray,NETCDF-4,cdf,False,tile_generation_failed,list index out of range,https://staging.openveda.cloud/api/titiler-cmr...,Wavelength,"[Wavelength, Time_Data, Irradiance]",21.0,2,None
309,C1231627223-GES_DISC,G1289992992-GES_DISC,GES_DISC,s3://gesdisc-cumulus-prod-protected/TRMM_RT/TR...,xarray,netCDF,nc4,False,tile_generation_failed,Expecting value: line 1 column 1 (char 0),https://staging.openveda.cloud/api/titiler-cmr...,precipitation,"[precipitation, precipitation_error, source, u...",57961.0,3,None
310,C1233767545-GES_DISC,G1415044909-GES_DISC,GES_DISC,s3://gesdisc-cumulus-prod-protected/GLDAS/GLDA...,xarray,netCDF,nc4,True,None,None,https://staging.openveda.cloud/api/titiler-cmr...,Swnet_tavg,"[time_bnds, Swnet_tavg, Lwnet_tavg, Qle_tavg, ...",195775.0,4,None
311,C1233767548-GES_DISC,G1414475414-GES_DISC,GES_DISC,s3://gesdisc-cumulus-prod-protected/GLDAS/GLDA...,xarray,netCDF,nc4,True,None,None,https://staging.openveda.cloud/api/titiler-cmr...,Swnet_tavg,"[time_bnds, Swnet_tavg, Lwnet_tavg, Qle_tavg, ...",195775.0,4,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10618,C3826284331-NSIDC_CPRD,G3838381861-NSIDC_CPRD,NSIDC,s3://nsidc-cumulus-prod-protected/ATLAS/ATL21/...,xarray,None,h5,False,no_xy_dimensions,Couldn't find X/Y dimensions in (),https://staging.openveda.cloud/api/titiler-cmr...,crs,"[crs, grid_lat, grid_lon, land_mask_map]",162.0,3,None
10620,C3834287411-ORNL_CLOUD,G3835158118-ORNL_CLOUD,ORNLDAAC,s3://ornl-cumulus-prod-protected/shift/SHIFT_A...,xarray,netCDF-4,nc,False,no_xy_dimensions,Couldn't find X/Y dimensions in (),https://staging.openveda.cloud/api/titiler-cmr...,transverse_mercator,[transverse_mercator],1593.0,2,None
10621,C3834287416-ORNL_CLOUD,G3845354168-ORNL_CLOUD,ORNLDAAC,s3://ornl-cumulus-prod-protected/shift/SHIFT_A...,xarray,netCDF-4,nc,False,no_xy_dimensions,"Couldn't find X/Y dimensions in ('lines', 'sam...",https://staging.openveda.cloud/api/titiler-cmr...,lat,"[lat, lon, elev, transverse_mercator]",1598.0,1A,None
10623,C3838944284-GHRC_DAAC,G3842115505-GHRC_DAAC,GHRCDAAC,s3://ghrcw-protected/isslis_v3_fin__3/ISS_LIS_...,xarray,NETCDF-4,nc,False,tile_generation_failed,b'\x0e\x03\x13\x01\x01\x00\x00\x0e' is not the...,https://staging.openveda.cloud/api/titiler-cmr...,raster_image,"[raster_image, raster_image_color_table, orbit...",72828.0,2,None
10625,C3845712819-NSIDC_CPRD,G3846532557-NSIDC_CPRD,NSIDC,s3://nsidc-cumulus-prod-protected/ICEBRIDGE-Re...,xarray,None,nc,False,no_xy_dimensions,Couldn't find X/Y dimensions in (),https://staging.openveda.cloud/api/titiler-cmr...,mapping,"[mapping, depth_iso, depth_std, age_norm, age_...",1.0,4,None

In [25]:
result = subset_df[(subset_df.incompatible_reason == 'tile_generation_failed') & 
                   (subset_df['error_message'].str.contains('No variable named', na=False))]

In [26]:
result

,collection_concept_id,concept_id,data_center,data_url,backend,format,extension,tiling_compatible,incompatible_reason,error_message,tiles_url,variable,data_variables,num_granules,processing_level,groups
2711,C1979602587-GHRC_DAAC,G1979602676-GHRC_DAAC,GHRCDAAC,s3://ghrcw-protected/gpmhiwrapiphx__1/IPHEX_HI...,xarray,NETCDF-4,nc,False,tile_generation_failed,"""No variable named 'altitude'. Variables on th...",https://staging.openveda.cloud/api/titiler-cmr...,altitude,"[altitude, dopcorr, evel, gatesp, gspeed, head...",210.0,1B,None
3156,C1995568158-GHRC_DAAC,G2768006300-GHRC_DAAC,GHRCDAAC,s3://ghrcw-protected/goesimpacts__1/IMPACTS_go...,xarray,NETCDF-4,nc,False,tile_generation_failed,"""No variable named 'Rad'. Variables on the dat...",https://staging.openveda.cloud/api/titiler-cmr...,Rad,"[Rad, DQF, time_bounds, goes_imager_projection...",848057.0,3,None
3194,C1995869065-GHRC_DAAC,G1997644304-GHRC_DAAC,GHRCDAAC,s3://ghrcw-protected/sbuceilimpacts__1/IMPACTS...,xarray,netCDF-4,nc,False,tile_generation_failed,"""No variable named 'latitude'. Did you mean on...",https://staging.openveda.cloud/api/titiler-cmr...,latitude,"[latitude, longitude, azimuth, zenith, altitud...",15836.0,2,None
4121,C2216863856-ORNL_CLOUD,G2217349171-ORNL_CLOUD,ORNLDAAC,s3://ornl-cumulus-prod-protected/global_soil/H...,xarray,None,nc4,False,tile_generation_failed,"""No variable named 'S_PH_H2O'. Did you mean on...",https://staging.openveda.cloud/api/titiler-cmr...,S_PH_H2O,[S_PH_H2O],28.0,4,None
4314,C2254805714-POCLOUD,G2777006404-POCLOUD,PODAAC,s3://podaac-ops-cumulus-protected/SAILDRONE_AR...,xarray,netCDF-4,nc,False,tile_generation_failed,"""No variable named 'roll'. Variables on the da...",https://staging.openveda.cloud/api/titiler-cmr...,roll,"[roll, pitch, heading, vel_east, vel_north, ve...",4.0,2,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10461,C3620140295-OB_CLOUD,G3748132880-OB_CLOUD,OBDAAC,s3://ob-cumulus-prod-public/PACE_OCI.20250419....,xarray,netCDF-4,nc,False,tile_generation_failed,"""No variable named 'aph_unc_442'. Did you mean...",https://staging.openveda.cloud/api/titiler-cmr...,aph_unc_442,"[aph_unc_442, palette]",14580.0,3,None
10585,C3779578929-OB_CLOUD,G3812672335-OB_CLOUD,OBDAAC,s3://ob-cumulus-prod-public/JPSS2_VIIRS.202510...,xarray,netCDF-4,nc,False,tile_generation_failed,"""No variable named 'adg_s'. Variables on the d...",https://staging.openveda.cloud/api/titiler-cmr...,adg_s,"[adg_s, palette]",2772.0,3,None
10586,C3779578995-OB_CLOUD,G3801383694-OB_CLOUD,OBDAAC,s3://ob-cumulus-prod-public/JPSS2_VIIRS.202408...,xarray,netCDF-4,nc,False,tile_generation_failed,"""No variable named 'a_411'. Variables on the d...",https://staging.openveda.cloud/api/titiler-cmr...,a_411,"[a_411, palette]",41868.0,3,None
10595,C3779579730-OB_CLOUD,G3799232446-OB_CLOUD,OBDAAC,s3://ob-cumulus-prod-public/JPSS2_VIIRS.202509...,xarray,netCDF-4,nc,False,tile_generation_failed,"""No variable named 'angstrom'. Variables on th...",https://staging.openveda.cloud/api/titiler-cmr...,angstrom,"[angstrom, palette]",1078.0,3,None
10596,C3779579762-OB_CLOUD,G3803253048-OB_CLOUD,OBDAAC,s3://ob-cumulus-prod-public/JPSS2_VIIRS.202301...,xarray,netCDF-4,nc,False,tile_generation_failed,"""No variable named 'angstrom'. Variables on th...",https://staging.openveda.cloud/api/titiler-cmr...,angstrom,"[angstrom, palette]",16282.0,3,None

In [ ]:
all_unique_vars = set().union(*result.data_variables)

keywords = ['time', 'latitude', 'longitude', 'num_obs', 'foo', 'crs', 'missing', 'palette', 'scaling', 'base', 'profile', 'error_ext', 'error_vel']
filtered_list = [item for item in all_unique_vars if not any(keyword in item.lower() for keyword in keywords)]
print(len(filtered_list))

539

In [29]:
with open('titiler_cmr_compatibility/known_vars.txt', 'w') as f:
    for item in filtered_list:
        f.write(f"{item}\n")

In [11]:
# !aws s3 cp s3://nasa-veda-scratch/aimee/tiling_results.parquet \
#     s3://nasa-veda-scratch/aimee/tiling_results_11-08-2025.parquet

copy: s3://nasa-veda-scratch/aimee/tiling_results.parquet to s3://nasa-veda-scratch/aimee/tiling_results_11-08-2025.parquet